name: CMake cross-platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        include:
          - os: windows-latest
            build_type: Release

          - os: ubuntu-latest
            c_compiler: gcc-13
            cpp_compiler: g++-13

          - os: ubuntu-latest
            c_compiler: clang-17
            cpp_compiler: clang++-17

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC 13
        if: matrix.cpp_compiler == 'g++-13'
        run: |
          sudo apt update
          sudo apt install -y gcc-13 g++-13

      - name: Install Clang 17
        if: matrix.cpp_compiler == 'clang++-17'
        run: |
          sudo apt update
          sudo apt install -y clang-17

      - name: Configure (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: >
          cmake -B build
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S .

      - name: Configure (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir build --build-config ${{ matrix.build_type }}